### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Frosxc** [Nightfall-MCPE/NightfallProtocols#17]
PocketMine-MP version: 5.20.0 [Protocol 748]
Git commit: 4b06f65ae4a24f8f045d089db55c9b5d657887fb-dirty
PHP version: 8.2.17
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: NightfallProtocol

Thread: Main
Error: pocketmine\network\mcpe\protocol\types\PlayerMovementSettings::__construct(): Argument #1 ($movementType) must be of type int, pocketmine\network\mcpe\protocol\types\ServerAuthMovementMode given, called in /home/container/plugins/NightfallProtocols-main/src/Supero/NightfallProtocol/network/handlers/CustomPreSpawnPacketHandler.php on line 80
File: pmsrc/vendor/pocketmine/bedrock-protocol/src/types/PlayerMovementSettings
Line: 20
Type: TypeError
Backtrace:
#0 plugins/NightfallProtocols-main/src/Supero/NightfallProtocol/network/handlers/CustomPreSpawnPacketHandler(80): pocketmine\network\mcpe\protocol\types\PlayerMovementSettings->__construct(object pocketmine\network\mcpe\protocol\types\ServerAuthMovementMode#1153720, int 0, false)
#1 pmsrc/src/network/mcpe/NetworkSession(342): Supero\NightfallProtocol\network\handlers\CustomPreSpawnPacketHandler->setUp()
#2 plugins/NightfallProtocols-main/src/Supero/NightfallProtocol/network/CustomNetworkSession(130): pocketmine\network\mcpe\NetworkSession->setHandler(object Supero\NightfallProtocol\network\handlers\CustomPreSpawnPacketHandler#1148830)
#3 pmsrc/src/network/mcpe/NetworkSession(941): Supero\NightfallProtocol\network\CustomNetworkSession->setHandler(object Supero\NightfallProtocol\network\handlers\CustomPreSpawnPacketHandler#1148830)
#4 pmsrc/src/network/mcpe/NetworkSession(293): pocketmine\network\mcpe\NetworkSession->beginSpawnSequence()
#5 pmsrc/src/promise/Promise(47): pocketmine\network\mcpe\NetworkSession->onPlayerCreated(object pocketmine\player\Player#1138446)
#6 pmsrc/src/network/mcpe/NetworkSession(248): pocketmine\promise\Promise->onCompletion(object Closure#1141563, object Closure#1153287)
#7 plugins/NightfallProtocols-main/src/Supero/NightfallProtocol/network/CustomNetworkSession(271): pocketmine\network\mcpe\NetworkSession->createPlayer()
#8 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(182): Supero\NightfallProtocol\network\CustomNetworkSession->Supero\NightfallProtocol\network\{closure}()
#9 pmsrc/vendor/pocketmine/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#1153270)
#10 plugins/NightfallProtocols-main/src/Supero/NightfallProtocol/network/CustomNetworkSession(450): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#1144407)
#11 plugins/NightfallProtocols-main/src/Supero/NightfallProtocol/network/CustomNetworkSession(383): Supero\NightfallProtocol\network\CustomNetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#1153270, string[4] ....)
#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(214): Supero\NightfallProtocol\network\CustomNetworkSession->handleEncoded(string[6] ......)
#13 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[15] .......P.g>....)
#14 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object Supero\NightfallProtocol\network\CustomRaklibInterface#1095636)
#15 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
#17 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
#18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#19 pmsrc/src/Server(1698): pocketmine\snooze\SleeperHandler->sleepUntil(float 1730184006.6903)
#20 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
#21 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#22 pmsrc/src/PocketMine(378): pocketmine\server()
#23 /home/container/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMPj05ujJ.tar/src/PocketMine.php)

Code:
[11]  */
[12] 
[13] declare(strict_types=1);
[14] 
[15] namespace pocketmine\network\mcpe\protocol\types;
[16] 
[17] use pocketmine\network\mcpe\protocol\serializer\PacketSerializer;
[18] 
[19] final class PlayerMovementSettings{
[20] 	public function __construct(
[21] 		private int $movementType,
[22] 		private int $rewindHistorySize,
[23] 		private bool $serverAuthoritativeBlockBreaking
[24] 	){}
[25] 
[26] 	public function getMovementType() : int{ return $this->movementType; }
[27] 
[28] 	public function getRewindHistorySize() : int{ return $this->rewindHistorySize; }
[29] 
[30] 	public function isServerAuthoritativeBlockBreaking() : bool{ return $this->serverAuthoritativeBlockBreaking; }

**Comment by Superomarking** [comment]
Changes for PreSpawnPacketHandler weren't fully updated, give me a moment

**Comment by Superomarking** [comment]
nvm, make sure pm is updated properly.

**Comment by Frosxc** [comment]
alr wait i will try it
